// ---------------------------------------------------------------------------
// Shared TypeScript types used across the voice agent
// ---------------------------------------------------------------------------

/** The tool names the Vapi assistant is allowed to call. */
export type ToolName =
  | "check_availability"
  | "book_appointment"
  | "lookup_faq"
  | "log_lead"
  | "send_confirmation";

/** Payload sent by Vapi when the LLM invokes a tool. */
export interface FunctionCallPayload {
  /** Name of the tool being called. */
  name: ToolName;
  /** Arguments supplied by the LLM, parsed as a plain object. */
  parameters: Record<string, unknown>;
}

/** Payload sent by Vapi at the end of a call. */
export interface EndOfCallReport {
  /** Human-readable summary generated by the LLM. */
  summary: string;
  /** Full transcript of the call. */
  transcript: string;
  /** Duration of the call in seconds. */
  durationSeconds: number;
  /** Caller phone number in E.164 format. */
  callerPhone?: string;
  /** Cost of the call in USD. */
  costUsd?: number;
}

/** Shape of a calendar time slot returned to the caller. */
export interface TimeSlot {
  start: string; // ISO 8601
  end: string; // ISO 8601
  display: string; // human-friendly, e.g. "Monday Jan 15, 10:00 AM - 10:30 AM"
}

/** Shape of a booked appointment. */
export interface BookingConfirmation {
  eventId: string;
  calendarLink: string;
  dateTime: string;
  service: string;
  patientName: string;
}

/** A single FAQ entry stored in the knowledge base. */
export interface FaqEntry {
  question: string;
  answer: string;
  category: string;
}

/** Result from a RAG knowledge base query. */
export interface KnowledgeResult {
  answer: string;
  score: number;
  category: string;
}

/** Contact record used for CRM operations. */
export interface ContactRecord {
  phone: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  serviceInterest?: string;
  callNotes?: string;
}

/** Notification request after a call ends. */
export interface NotificationRequest {
  phone: string;
  email?: string;
  patientName: string;
  appointmentTime?: string;
  service?: string;
  businessName: string;
  businessAddress: string;
}

/** Vapi webhook event types we handle. */
export type VapiWebhookType =
  | "assistant-request"
  | "function-call"
  | "end-of-call-report"
  | "status-update";

/** Generic Vapi webhook message envelope. */
export interface VapiWebhookMessage {
  message: {
    type: VapiWebhookType;
    [key: string]: unknown;
  };
}
